### ISSUE TITLE
FlexSearch is not defined

### ISSUE THREAD

**Issue by torfjelde** [JuliaComputing/MultiDocumenter.jl#39]
When I access https://juliacomputing.github.io/MultiDocumenter.jl/ I see the error

```javascript
flexsearch_integration.js:4 Uncaught ReferenceError: FlexSearch is not defined
    at flexsearch_integration.js:4:27
    at flexsearch_integration.js:172:3
```

which breaks the global search. I can verify that `FlexSearch` is defined in the console after the page has loaded so seems like `FlexSearch` isn't loaded prior to `flexsearch_integration.js` being evaluated.

**Comment by torfjelde** [comment]
Seems like 

https://github.com/JuliaComputing/MultiDocumenter.jl/blob/a030360b2680a359125058bdc79b0475c51150dc/src/search/flexsearch.jl#L96-L99

is the cause?

Should be fixed if we simply re-order these statements so the flexsearch bundle is loaded before the flexsearch integration?
